import mongoose from "mongoose";

const quizAttemptSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  skill: {
    type: String,
    enum: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Vue.js",
      "Angular",
      "Node.js",
      "Express.js",
      "HTML",
      "CSS",
      "MongoDB",
      "MySQL",
      "PostgreSQL",
      "Firebase",
      "Laravel",
      "PHP",
      "Git",
      "REST API",
      "GraphQL",
      "Python",
      "Django",
      "SQL",
      "UI/UX Design",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Figma",
      "Canva",
      "Content Writing",
      "Copywriting",
      "Technical Writing",
      "Communication",
      "Problem Solving",
      "Project Management",
      "SEO",
      "Email Marketing",
      "Digital Marketing",
      "Google Ads",
      "Facebook Ads",
      "WordPress",
      "Shopify",
      "E-commerce",
      "Blockchain",
      "Web3",
      "Data Structures",
      "Algorithms",
      "Machine Learning",
      "Data Science",
      "Cybersecurity",
      "DevOps",
      "Docker",
      "Kubernetes",
    ],
    required: true,
  },
  difficulty: {
    type: String,
    enum: ["easy", "medium", "hard"],
    required: true,
  },
  questions: [
    {
      questionText: String,
      options: [String],
      correctAnswer: String,
      selectedAnswer: { type: String, default: "" },
      isCorrect: Boolean,
      isEmpty: Boolean,
      timeTaken: Number, // in seconds
    },
  ],
  totalQuestions: Number,
  correctAnswers: Number,
  wrongAnswers: Number,
  emptyAnswers: Number,
  percentage: Number,
  learningLevel: {
    type: String,
    enum: ["Beginner", "Intermediate", "Advanced", "Expert"],
    default: "Beginner",
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const QuizAttempt = mongoose.model("QuizAttempt", quizAttemptSchema);
export default QuizAttempt;
